config/routes.rb
# require 'sidekiq/web'
AutoshinaKg::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  # mount Sidekiq::Web => '/sidekiq'
  # authenticate :admin_user do
  #   mount Sidekiq::Web => '/admin/sidekiq'
  # end

  get 'api/products', to: 'api#products'
  get 'api/categories', to: 'api#categories'
  get 'api/categories_fields', to: 'api#categories_fields'
  get 'api/categories_fields_values', to: 'api#categories_fields_values'
  get 'api/products_fields_values', to: 'api#products_fields_values'
  get 'api/parts', to: 'api#parts'
  get 'api/vendors', to: 'api#vendors'


  # get 'products/search', :as => 'search'
  get 'pages/calculator', :as => 'calculator'
  get 'products/fetch_fields', :as => 'fetch_fields'
  get 'products/fetch_field_type', :as => 'fetch_field_type'
  get 'products/conversion_of_currency', :as => 'conversion_of_currency'
  get 'products/update_categories', :as => 'update_categories'
  get 'products/fetch_vendors', :as => 'fetch_vendors'
  get 'products/fetch_product_fields', :as => 'fetch_product_fields'
  get 'products/fetch_fields_sizes', :as => 'fetch_fields_sizes'
  resources :products
  resources :cars
  root 'products#index'
  resources :news_items, path: 'news', only: [:index, :show]
  resources :offer_items, path: 'offers', only: [:index, :show]
  get '/contacts', to: 'pages#contacts'
  get '/about', to: 'pages#about'
  get '/deliver', to: 'pages#deliver'
  get '/rules', to: 'pages#rules'
  get 'vendors/update_vendors', :as => 'update_vendors'
  get 'vendors/select_vendors', :as => 'select_vendors'
  get 'car_models/fetch_models', :as => 'fetch_models'
  get 'categories_fields_values/fetch_categories_fields_values', :as => 'fetch_categories_fields_values'
  get 'categories_fields_values/set_categories_fields_values', :as => 'set_categories_fields_values'
  get 'car_models/fetch_car_models', :as => 'fetch_car_models'
  get 'car_models/fetch_years', :as => 'fetch_years'
  get 'car_models/fetch_modifications', :as => 'fetch_modifications'
  get 'car_models/fetch_sizes', :as => 'fetch_sizes'
  resources :orders, only: [:update, :show, :destroy, :edit]
  resources :order_items, only: [:create, :destroy, :update]
  resources :bookmarks, only: [:update, :show, :destroy]
  resources :bookmark_items, only: [:create, :destroy]
  # resource :order, only: [:update, :show, :destroy] do
  #   resources :order_items, only: [:create, :destroy, :update]
  # end

  get 'payment/cancelled', to: 'payments#cancelled'
  post 'payment/result', to: 'payments#result'
  get 'payment/connection_failed', to: 'payments#connection_failed'

  # get "/system/*path", to: redirect('http://autoshina.kg/system/%{path}.%{format}') if Rails.env.development? && !ENV['ASSETS_HOST']
end

app/views/shared/_banner.html.slim
-if Banner.where("active = TRUE AND site = 'banner'").count > 0
  - path = Banner.where("active = TRUE AND site = 'banner'").last.file.url
  -if MIME::Types.type_for(path).first.content_type == "application/x-shockwave-flash"
          <object width="840" height="109">
          <param name="movie" value="#{path}">
          <embed src="#{path}" width="840" height="109">
          </embed>
          </object>
  - else
    -unless Banner.where("active = TRUE AND site = 'banner'").last.link.blank?
      = link_to (image_tag (Banner.where("active = TRUE AND site = 'banner'").last.file.banner.url)), Banner.where("active = TRUE AND site = 'banner'").last.link, class: "banner"
    -else
      = image_tag (Banner.where("active = TRUE AND site = 'banner'").last.file.banner.url), class: "banner"

app/views/shared/_breadcrumbs.html.slim
.breadcrumbs
  -if params[:controller] == "orders" && params[:action] == "edit"
    .title
      h1 Оформление заказа
  -else
    ul
      li = link_to "Главная", root_path
      -if params[:controller] == "products" && params[:action] == "show"
        -if @product.part.id == 1
          li = link_to "Каталог шин", products_path( search_type: {part_id: 1})
        -elsif @product.part.id == 2
          li = link_to "Каталог масел", products_path( search_type: {part_id: 2})
        -elsif @product.part.id == 3
          li = link_to "Каталог аккумуляторов", products_path( search_type: {part_id: 3})
        -elsif @product.part.id == 4
          li = link_to "Каталог дисков", products_path( search_type: {part_id: 4})
        li = link_to "#{@product.category.name}", products_path( search_type: {category_id: @product.category.id})
        li = link_to "#{@product.vendor.name}", products_path( search_type: {vendor_id: @product.vendor.id})
        li = "#{@product.name}"
      -elsif params[:controller] == "pages"
        li = "#{@page_name}"
      -elsif params[:controller] == "news_items" && params[:action] == "index"
        li = "#{@page_name}"
      -elsif params[:controller] == "news_items" && params[:action] == "show"
        li = link_to "#{@page_name}", news_items_path
        li.short = "#{@news_item.title}"
      -elsif params[:controller] == "offer_items" && params[:action] == "index"
        li = "#{@page_name}"
      -elsif params[:controller] == "offer_items" && params[:action] == "show"
        li = link_to "#{@page_name}", offer_items_path
        li.short = "#{@offer_item.title}"

app/views/shared/_currency.html.slim
- if cookies[:currency] == "dollar"
  li= link_to "Сомы", conversion_of_currency_path
  li Доллары
-else
  li Сомы
  li= link_to "Доллары", conversion_of_currency_path

app/views/shared/_featured_products.html.slim
.featured
  .product_slider
    .title
      h1 Популярные шины 
    .slider_box
      - @featured.in_groups_of(5).each do |group|
        .slide
          - group.each do |product|
            -if product.nil?
              -product = Product.price_exists.where(part_id: 1).sample
            / -binding.pry
            .product_slide
              .p_icons
                - if product.featured > 50
                  .pop
                - if product.discount > 0
                  .dis
                - if @bookmark.products.include? product
                  .bmarks
              = link_to image_tag(product.image.url :thumb), product, class: "show_prev"
              = link_to "Просмотр", product, class: "preview", remote: true
              .title_product
                h2 = link_to product.vendor.name, product
                h2 
                  span.grad
                  = link_to product.name, product, title: "#{product.name}", class: "hover"
              p = "Размер: #{product.internal_name}"
              - if product.discount > 0
                p.pink = "Акция: <strong>#{discount product}</strong>".html_safe
              -else
                p = "Цена: <strong>#{currency_checked product}</strong>".html_safe

      a href="#" class="slidesjs-previous slidesjs-navigation"
      a href="#" class="slidesjs-next slidesjs-navigation"

app/views/shared/_filter.html.slim
.filter
  .title
    h1 Поиск
  .search
    = form_tag(products_path, :method => "get") do |f|
      .search_type

        = radio_button_tag "search_type[part_id]" , "1", tires_checked?
        = label_tag :search_type_part_id_1, "", class: "f_tr #{'check' if tires_checked?}"
        = radio_button_tag  "search_type[part_id]", "2", oils_checked?
        = label_tag :search_type_part_id_2, "", class: "f_oil #{'check' if oils_checked?}"
        = radio_button_tag  "search_type[part_id]", "3", accumulator_checked?
        = label_tag :search_type_part_id_3, "", class: "f_acc #{'check' if accumulator_checked?}"
        = radio_button_tag  "search_type[part_id]", "4", rim_checked?
        = label_tag :search_type_part_id_4, "", class: "f_rm #{'check' if rim_checked?}"
      .search_fields
        .tire.active
          .tire_or_car
            = radio_button_tag :search_of , "tire_type",checked: true
            = label_tag :search_of_tire_type, "По типу шин"
            = radio_button_tag  :search_of , "car_type"
            = label_tag :search_of_car_type, "По марке автомобиля"
          .fields
            .tire_type.active
              / = select_tag "search_type[category_id]", options_for_select((Category.where(part_id: "1").map { |c| [c.name, c.id] }), category_checked), {id: 'tire_category'}
              .tire_fields
                / -binding.pry
                = select_tag "search_type[vendor_id]", options_for_select(tire_vendors,vendor_checked), {id: 'tire_vendor'}
                -if params[:search_type].present? and params[:search_type][:part_id] == '1' and params[:search_type][:category_id].present?
                  / -binding.pry
                  - fields = Category.find(params[:search_type][:category_id]).categories_fields.where(show_in_browse: "1") unless params[:search_type][:category_id].nil?
                  - fields.where(search_type: "select").each do |field|
                    - values = field.categories_fields_values.order("value asc").to_a.sort_by! {|s| s.value.scan(/\d+/)[0].to_i}
                    = select_tag "search_size[field_#{field.id}]", options_for_select((values.map { |c| [c.value, c.value] }).insert(0, ["#{field.field_name}", ""]), category_fields_select(field.id)), {id: "field_#{field.id}"}
                -else
                  - fields = Category.first.categories_fields.where(show_in_browse: "1")
                  - fields.where(search_type: "select").each do |field|
                    - values = field.categories_fields_values.order("value asc").to_a.sort_by! {|s| s.value.scan(/\d+/)[0].to_i}
                    = select_tag "search_size[field_#{field.id}]", options_for_select((values.map { |c| [c.value, c.value] }).insert(0, ["#{field.field_name}", ""])), {id: "field_#{field.id}"}

              .tire_checkbox
                / -binding.pry
                - fields.where(search_type: "checkbox").each do |field|
                  - values = field.categories_fields_values
                  - values.each do |v|
                    .checkbox_field
                      = check_box_tag "search_season[#{v.value}]", nil, category_fields_checked(v.value) ,id: "checkbox_#{v.id}"
                      = label_tag "checkbox_#{v.id}", "#{v.value}"



              / = select_tag "search[category_id]", options_for_select((Category.where(part_id: "1").map { |c| [c.name, c.id] }).insert(0, ["Тип автомобиля", ""])), {id: 'tire_category'}
              / = select_tag "search[vendor_id]", options_for_select((Vendor.all.map { |v| [v.name, v.id] }).insert(0, ["Производитель", ""])),{id: 'tire_vendor'}
              = submit_tag("Поиск")
            .models
              = select_tag "search_car[manufacturer]", options_for_select((CarManufacturer.all.order(:title).map { |c| [c.title, c.id] }).insert(0, ["Производитель", ""])), {id: 'car_manufacturer'}
              = select_tag "search_car[model]", options_for_select([["Модель",""]]), {id: 'car_model',disabled: true}
              = select_tag "search_car[year]", options_for_select([["Год выпуска", ""]]), {id: 'car_year',disabled: true}
              = select_tag "search_car[modification]", options_for_select([["Модификация", ""]]), {id: 'car_modification',disabled: true}
              <input type="button" value="Поиск">
        .oil
          .oil_type
            = select_tag "search_type[category_id]", options_for_select((Category.where(part_id: "2").map { |c| [c.name, c.id] }), category_checked),{id: 'oil_category'}
            .oil_fields
              / = select_tag "search_type[vendor_id]", options_for_select((Category.find(params[:search_type][:category_id]).vendors.map { |c| [c.name, c.id] }).insert(0, ["Производитель", ""]),vendor_checked), {id: 'tire_vendor'}
              = select_tag "search_type[vendor_id]", options_for_select(oil_vendors,vendor_checked), {id: 'tire_vendor'}
              -if params[:search_type].present? and params[:search_type][:part_id] == '2' and params[:search_type][:category_id].present?
                  - fields = Category.find(params[:search_type][:category_id]).categories_fields.where(show_in_browse: "1") unless params[:search_type][:category_id].nil?
                  - fields.where(search_type: "select").each do |field|
                    - values = field.categories_fields_values
                    = select_tag "search_size[field_#{field.id}]", options_for_select((values.order("value asc").map { |c| [c.value, c.value] }).insert(0, ["#{field.field_name}", ""]), category_fields_select(field.id)), {id: "field_#{field.id}"}
              -else
                - fields = Category.where(part_id: 2).first.categories_fields.where(show_in_browse: "1")
                - fields.where(search_type: "select").each do |field|
                  - values = field.categories_fields_values
                  = select_tag "search_size[field_#{field.id}]", options_for_select((values.order("value asc").map { |c| [c.value, c.value] }).insert(0, ["#{field.field_name}", ""])), {id: "field_#{field.id}"}
            .oil_checkbox
            / = select_tag "search[vendor_id]", options_for_select((Vendor.all.map { |v| [v.name, v.id] }).insert(0, ["Производитель", ""])),{id: 'oil_vendor'}
          = submit_tag("Поиск")
        .battery
          .battery_type
            .battery_fields
              = select_tag "search_type[vendor_id]", options_for_select(battery_vendors,vendor_checked), {id: 'battery_vendor'}
              - fields = Category.where(part_id: 3).first.categories_fields.where(show_in_browse: "1")
              - fields.where(search_type: "select").each do |field|
                - values = field.categories_fields_values
                = select_tag "search_size[field_#{field.id}]", options_for_select((values.order("value asc").map { |c| [c.value, c.value] }).insert(0, ["#{field.field_name}", ""]), category_fields_select(field.id)), {id: "field_#{field.id}"}
            .battery_checkbox
          = submit_tag("Поиск")
        .rim
          .rim_type
            .rim_fields
              = select_tag "search_type[vendor_id]", options_for_select(rim_vendors,vendor_checked), {id: 'rim_vendor'}
              - fields = Category.where(part_id: 4).first.categories_fields.where(show_in_browse: "1")
              - fields.where(search_type: "select").each do |field|
                - values = field.categories_fields_values
                = select_tag "search_size[field_#{field.id}]", options_for_select((values.order("value asc").map { |c| [c.value, c.value] }).insert(0, ["#{field.field_name}", ""]), category_fields_select(field.id)), {id: "field_#{field.id}"}
            .rim_checkbox
          = submit_tag("Поиск")

      .payment-system
        .payment-system__title
          h5 Принимаем к оплате
        = image_tag("elcart.png")


  -unless Banner.where("active = TRUE AND site = 'catalog'").blank?
    - Banner.where("active = TRUE AND site = 'catalog'").each do |banner|
      = link_to (image_tag banner.file.catalog_placeholder.url), banner.link, class: "banner"

app/views/shared/_footer.html.slim
.footer
  .wrapper
    .flogo
      = link_to image_tag("logo_new.svg"), root_path
      / = link_to "Autoshina", root_path, class: "flogo_img"
      p.cop &#169; autoshina.kg 2009-2014
    .finfo
      p Пн.-Сб. 08:00-18:00
      p Вс. выходной
      / p 
      /   | Телефон: Бишкек 
      /   - @phones.each_with_index do |phone, i|
      /     a< [href="+#{phone}"] = " +#{phone}"
      /     - if i != @phones.length-1
      /       | ,
      p.no-mobile = @site_settings.phone
      p.show-mobile 
        | Телефон: Бишкек 
        - @phones.each_with_index do |phone, i|
          a< [href="tel:+#{phone}"] = "+#{phone}"
          - if i != @phones.length-1
            | ,
      p = "email: #{mail_to @site_settings.email}".html_safe
    .fmenu
      ul.left_menu
        li = link_to "Доставка", deliver_path
        li = link_to "Контакты", contacts_path
        li = link_to "О нас", about_path
        li = link_to "Правила", rules_path
      ul
        li = link_to "Шины", products_path( search_type: {part_id: 1})
        li = link_to "Масла", products_path( search_type: {part_id: 2})
        li = link_to "Диски", products_path( search_type: {part_id: 4})
        li = link_to "Аккумуляторы", products_path( search_type: {part_id: 3})
    .ficon
      p.bmarks Товар добавлен в закладки
      p.pop Популярный товар
      p.dis На данный товар действуют скидки

app/views/shared/_header.html.slim
.header
  = link_to "", root_path, id: "logo"
  .info
    ul
      li Режим работы:
      li Пн-Сб. 08:00-18:00
      li Вс. выходной
      li.no-mobile = @site_settings.phone
      li.show-mobile 
        | Телефон: Бишкек 
        - @phones.each_with_index do |phone, i|
          a< [href="tel:+#{phone}"] = "+#{phone}"
          - if i != @phones.length-1
            | ,
      li = "email: #{mail_to @site_settings.email}".html_safe
  .header_cart
    .currency
      ul
        = render "shared/currency"
      / p Закладки
      .bm
        / = link_to "Закладки", @bookmark, class: "bookmark_count", remote: true  
        =render "bookmarks/bookmark_link"
      .ct
        =render "orders/order_link"
  #message
    -if flash[:notice].present?
      = flash[:notice]

app/views/shared/_nav.html.slim
.nav-box
  .nav
    .menu
      ul
        li = link_to "Шины", products_path( search_type: {part_id: 1}),  class: "#{'active' if params[:controller] == 'products' and params[:search_type] and params[:search_type][:part_id] == '1'}"
        li = link_to "Масла", products_path( search_type: {part_id: 2}),  class: "#{'active' if params[:controller] == 'products' and params[:search_type] and params[:search_type][:part_id] == '2'}"
        li = link_to "Диски", products_path( search_type: {part_id: 4}),  class: "#{'active' if params[:controller] == 'products' and params[:search_type] and params[:search_type][:part_id] == '4'}"
        li = link_to "Аккумуляторы", products_path( search_type: {part_id: 3}),  class: "#{'active' if params[:controller] == 'products' and params[:search_type] and params[:search_type][:part_id] == '3'}"
        li = link_to "Калькулятор", calculator_path,  class: "#{'active' if params[:controller] == 'pages' and params[:action] == 'calculator'}"
        li = link_to "Доставка", deliver_path, class: "#{'active' if params[:controller] == 'pages' and params[:action] == 'deliver'}"
        li = link_to "Акции", offer_items_path, class: "#{'active' if params[:controller] == 'offer_items'} link--blue"
        li = link_to "О нас", about_path, class: "#{'active' if params[:controller] == 'pages' and params[:action] == 'about'}"
        li = link_to "Новости", news_items_path, class: "#{'active' if params[:controller] == 'news_items'}"
        li = link_to "Контакты", contacts_path, class: "#{'active' if params[:controller] == 'pages' and params[:action] == 'contacts'}"
        li = link_to "Правила", rules_path, class: "#{'active' if params[:controller] == 'pages' and params[:action] == 'rules'}"
    .social
        ul
            li = link_to image_tag("inst.svg"), "http://instagram.com/autoshina.kg"
            / li = link_to image_tag("tw.png"), "https://twitter.com/autoshinakg"
            li = link_to image_tag("face.svg"), "https://www.facebook.com/autoshina.kg"
            / li = link_to image_tag("ok.png"), "http://www.odnoklassniki.ru/group/56852959199276"

app/views/shared/_slider.html.slim
- if Banner.slides.any?
  -if Banner.slides.count > 1
    #slides
      - Banner.slides.each do |s|
        / - binding.pry
        -if MIME::Types.type_for(s.file.path).first.content_type == "application/x-shockwave-flash"
          <object width="1280" height="325">
          <param name="movie" value="#{s.file.url}">
          <embed src="#{s.file.url}" width="1280" height="325">
          </embed>
          </object>
        - else
          - unless s.link.blank?
            = link_to (image_tag s.file.slide.url), s.link
          -else
            = image_tag s.file.slide.url
      a href="#" class="slidesjs-previous slidesjs-navigation"
      a href="#" class="slidesjs-next slidesjs-navigation"
  -else
    #slide
      - unless Banner.slides.first.link.blank?
        = link_to (image_tag Banner.slides.first.file.slide.url), Banner.slides.first.link
      -else
        = image_tag Banner.slides.first.file.slide.url