config/routes.rb
# require 'sidekiq/web'
AutoshinaKg::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  # mount Sidekiq::Web => '/sidekiq'
  # authenticate :admin_user do
  #   mount Sidekiq::Web => '/admin/sidekiq'
  # end

  get 'api/products', to: 'api#products'
  get 'api/categories', to: 'api#categories'
  get 'api/categories_fields', to: 'api#categories_fields'
  get 'api/categories_fields_values', to: 'api#categories_fields_values'
  get 'api/products_fields_values', to: 'api#products_fields_values'
  get 'api/parts', to: 'api#parts'
  get 'api/vendors', to: 'api#vendors'


  # get 'products/search', :as => 'search'
  get 'pages/calculator', :as => 'calculator'
  get 'products/fetch_fields', :as => 'fetch_fields'
  get 'products/fetch_field_type', :as => 'fetch_field_type'
  get 'products/conversion_of_currency', :as => 'conversion_of_currency'
  get 'products/update_categories', :as => 'update_categories'
  get 'products/fetch_vendors', :as => 'fetch_vendors'
  get 'products/fetch_product_fields', :as => 'fetch_product_fields'
  get 'products/fetch_fields_sizes', :as => 'fetch_fields_sizes'
  resources :products
  resources :cars
  root 'products#index'
  resources :news_items, path: 'news', only: [:index, :show]
  resources :offer_items, path: 'offers', only: [:index, :show]
  get '/contacts', to: 'pages#contacts'
  get '/about', to: 'pages#about'
  get '/deliver', to: 'pages#deliver'
  get '/rules', to: 'pages#rules'
  get 'vendors/update_vendors', :as => 'update_vendors'
  get 'vendors/select_vendors', :as => 'select_vendors'
  get 'car_models/fetch_models', :as => 'fetch_models'
  get 'categories_fields_values/fetch_categories_fields_values', :as => 'fetch_categories_fields_values'
  get 'categories_fields_values/set_categories_fields_values', :as => 'set_categories_fields_values'
  get 'car_models/fetch_car_models', :as => 'fetch_car_models'
  get 'car_models/fetch_years', :as => 'fetch_years'
  get 'car_models/fetch_modifications', :as => 'fetch_modifications'
  get 'car_models/fetch_sizes', :as => 'fetch_sizes'
  resources :orders, only: [:update, :show, :destroy, :edit]
  resources :order_items, only: [:create, :destroy, :update]
  resources :bookmarks, only: [:update, :show, :destroy]
  resources :bookmark_items, only: [:create, :destroy]
  # resource :order, only: [:update, :show, :destroy] do
  #   resources :order_items, only: [:create, :destroy, :update]
  # end

  get 'payment/cancelled', to: 'payments#cancelled'
  post 'payment/result', to: 'payments#result'
  get 'payment/connection_failed', to: 'payments#connection_failed'

  # get "/system/*path", to: redirect('http://autoshina.kg/system/%{path}.%{format}') if Rails.env.development? && !ENV['ASSETS_HOST']
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id              :integer          not null, primary key
#  status          :string(255)      default("unconfirmed")
#  name            :string(255)
#  address         :string(255)
#  phone           :string(255)
#  order_date      :datetime
#  created_at      :datetime
#  updated_at      :datetime
#  email           :string(255)
#  payment_type    :string(255)      default("cash")
#  delivery_cost   :float
#  delivery_id     :integer
#  delivery_region :string(255)
#

class Order < ActiveRecord::Base
  has_many :order_items
  has_many :products, through: :order_items
  has_one :payment
  belongs_to :delivery

  STATUSES = %i( unconfirmed confirmed delivered canceled )
  OUTDATED_SINCE = 1.days

  scope :outdated, -> { where("updated_at < ?", Time.now - OUTDATED_SINCE ) }

  validates :phone, format: { with: /[\+]\d{3}[\s]\d{3}[\s]\d{3}[\s]\d{3}/, message: 'invalid number'}, on: :update
  validates :address, length: { minimum: 6}, on: :update
  validates_presence_of :name, :address, :email, on: :update
  validates_presence_of :delivery_id, on: :update

  STATUSES.each_with_index do |status, index|
    scope status, -> { where status: status }
  end


  def total_price
    order_items.inject(0) do |sum, item|
      sum += item.product_cost.to_f * item.quantity.to_i
    end
  end

  def total_discounted_price_som
    order_items.inject(0) do |sum, item|
      sum += item.total_discounted_price.to_f
    end
  end

  def total_discounted_price_usd
    convert_to_usd(total_discounted_price_som)
  end

  def currency_total_price
    order_items.inject(0) do |sum, item|
      sum += item.product.conversion_of_currency.to_f * item.quantity.to_i
    end
  end

  def discount_total_price_s
    order_items.inject(0) do |sum, item|
      sum += item.product.discount_price.to_f * item.quantity.to_i
    end
  end

  def discount_total_price_d
    order_items.inject(0) do |sum, item|
      sum += item.product.currency_and_discount.to_f * item.quantity.to_i
    end
  end

  def color
    case self.status
      when 'unconfirmed'
        :gray
      when 'confirmed'
        :blue
      when 'delivered'
        :green
      when 'canceled'
        :red
    end
  end

  def self.order_statuses
    statuses = STATUSES.each_with_index.map{|status, index| [I18n.t("#{status}"), status] }
    statuses.shift
    statuses
  end

  # def self.cleanup!
  #   unconfirmed.outdated.destroy_all
  # end

  def self.cleanup!
    outdated.unconfirmed.find_each do |order|
      if order.payment_type == 'cash'
        order.order_items.destroy_all
        order.destroy
      end
    end
  end

  def delivery_price_som
    delivery_cost.nil? ? 0 : delivery_cost
  end

  def delivery_price_usd
    convert_to_usd(delivery_price_som)
  end

  def total_cost_som
    total_discounted_price_som + delivery_price_som
  end

  def total_cost_usd
    convert_to_usd(total_cost_som)
  end

  def convert_to_usd(sum)
    sum/SiteSetting.find(1).current_rate
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    if @order.update order_params
      @order.update_attributes delivery_cost: @order.delivery.cost
      @order.update_attributes delivery_region: @order.delivery.region

      send_order_for_payment
    else
      render :edit
    end
  end

  def destroy
    if @order.order_items.destroy_all
      render :empty_cart
    else
      render nothing: true, status: 405
    end
  end

  private

  def order_params
    params.require(:order).permit :name, :address, :phone, :email, :delivery_id, :payment_type
  end

  def send_order_for_payment
    order_params[:payment_type] == 'cash' ? cash_payment : pay_with_card
  end

  def cash_payment
    @order.update_attributes status: "confirmed", order_date: DateTime.now
    order = Order.create!
    session[:order_id] = order.id
    featured_products = FeatureProduct.new(@order)
    featured_products.perform

    EmailNewOrderJob.perform_async(@order.id)
    #EmailCustomerJob.perform_in(5, @order.id)
    # render js: "window.location.pathname='#{URI(request.referer).path}'"
    redirect_to root_path
    # render :complete
    flash[:notice] = "Ваш заказ принят! В ближайшее время с Вами свяжутся"
  end

  def pay_with_card
    threed_secure = UseThreedSecure.new
    post_msg = set_payment_post_details

    transaction_id = threed_secure.get_transaction_ID(post_msg)

    if transaction_id == 'No response' || !transaction_id
      redirect_to payment_connection_failed_path
    else
      @order.create_payment(transaction_id: transaction_id)
      session[:transaction_id] = transaction_id

      redirect_to threed_secure.get_redirect_URL(transaction_id)
    end
  end

  def set_payment_post_details
    to_post = {}

    total_price = @order.total_discounted_price_som
    total_shipping = @order.delivery.cost

    total = (total_price + total_shipping).round(2)

    product_description = 'Оплата за : ' + @order.order_items.first.product_name

    to_post = {
      amount: (total * 100).ceil,
      currency: AppConstants::CURRENCY,
      desc: product_description,
      language: AppConstants::LANG,
      client_ip_addr: request.ip
    }

    to_post
  end
end

app/views/orders/_form.html.slim
.title
  h1 Оформление заказа
= form_for @order, remote: true do |f|
  -if @order.errors.any?
    ul.errors
      -@order.errors.messages.values.flatten.each do |msg|
        li = msg
  .form_field
    =f.text_field :name, placeholder: "Введите имя..."
  .form_field
    =f.text_field :address, placeholder: "Введите адрес..."
  .form_field
    =f.text_field :phone, placeholder: "Введите номер телефона..."
  .form_field
    =f.submit "Оформить"
.close_button &#x2715;

app/views/orders/_order_form.html.erb
<div class="user-order__card-or-cash">
  <%= f.radio_button(:payment_type, 'cash') %>
  <%= f.label :payment_type, "Наличными", value: "cash" %>
  <%= f.radio_button(:payment_type, 'card', checked: (payment_method == 'card')) %>
  <%= f.label :payment_type, "Платежной картой Элкарт", value: "card" %>
</div>
<div class="user-order__form">
  <div class="user-order__form-item">
    <%= f.text_field :name, placeholder: 'ФИО *' %>
    <% if @order.errors.messages[:name].present? %>
      <div class="form-errors js-form-errors__name">
        <ul>
          <li class="form-errors__item"><%= @order.errors.messages[:name].first %></li>
        </ul>
      </div>
    <% end %>
    <%= f.label :name, "Обязательно заполните ФИО" %>
  </div>
  <div class="user-order__form-item">
    <%= f.text_field :phone, placeholder: 'Номер телефона *', type: 'tel', data: { inputmask: "'mask': '+999 999 999 999', 'clearmaskonlostfocus': 'true'" }%>
    <% if @order.errors.messages[:phone].present? %>
      <div class="form-errors js-form-errors__phone">
        <ul>
          <li class="form-errors__item"><%= @order.errors.messages[:phone].first %></li>
        </ul>
      </div>
    <% end %>
    <%= f.label :phone, "Формат: +996 555 557 557" %>
  </div>
  <div class="user-order__form-item">
    <%= f.text_field :email, placeholder: 'Адрес электронной почты *', type: 'email'%>
    <% if @order.errors.messages[:email].present? %>
      <div class="form-errors js-form-errors__email">
        <ul>
          <li class="form-errors__item"><%= @order.errors.messages[:email].first %></li>
        </ul>
      </div>
    <% end %>
    <%= f.label :email, "Email необходимо указать для получения уведомлений о статусе оплаты. Например: almaz1982@yandex.ru" %>
  </div>
  <div class="user-order__form-item">
    <div class="user-order__select">
       <%= f.select :delivery_id, options_for_select(Delivery.all.map { |d| [d.region, d.id, { 'data-delivery-cost' => d.cost }] }, selected: delivery_region_id ), { prompt: "Место доставки *" }, { class: "js-select-deleviry" } %>
       <% if @order.errors.messages[:delivery_id].present? %>
        <div class="form-errors js-form-errors__delivery_id">
          <ul>
            <li class="form-errors__item"><%= @order.errors.messages[:delivery_id].first %></li>
          </ul>
        </div>
      <% end %>
      <%= f.label :delivery, "В случае, если в предоставленном списке нет Вашего региона, то Вам нужно выбрать пункт «Нет моего региона» и уточнить стоимость доставки у нашего менеджера по телефону: <br><b>+996 555 00 15 39</b>".html_safe %>
    </div>
  </div>
  <div class="user-order__form-item">
    <%= f.text_area :address, placeholder: "Адрес доставки *", size: "30x10" %>
    <% if @order.errors.messages[:address].present? %>
      <div class="form-errors js-form-errors__address">
        <ul>
          <li class="form-errors__item"><%= @order.errors.messages[:address].first %></li>
        </ul>
      </div>
    <% end %>
    <%= f.label :address, "Укажите точный адрес доставки. Например: Нарния!" %>
  </div>
</div>
<%= f.hidden_field(:total_price, value: @order.total_price ) %>

app/views/orders/_order_link.html.slim
-if @order.order_items.any? 
  = link_to "Корзина <strong>#{total_price @order}</strong> (#{@order.order_items.count})".html_safe, @order, class: "cart_count", remote: true  
  = link_to "", order_path(@order),id: "clear_cart", method: :delete, remote: true
-else
  = link_to "Корзина пуста", "#", class: "cart_count"

app/views/orders/_order_total.html.erb
<h3 class="total-order__title">Итог заказа</h3>
<div class="total-order__inner">
  <div class="total-order__cols">
    <div class="total-order__col">
      <div class="total-order__text">Единиц товара (<%= @order.order_items.count %>):</div>
    </div>
    <div class="total-order__col">
      <div class="total-order__price js-order-price"><span><%= "%.2f" % @order.discount_total_price_s %></span> сом.</div>
    </div>
  </div>
  <div class="total-order__cols">
    <div class="total-order__col">
      <div class="total-order__text">Доставка:</div>
    </div>
    <div class="total-order__col">
      <div class="total-order__price js-delivery-cost"><span><%= delivery_cost.to_f %></span> сом.</div>
    </div>
  </div>
</div>
<div class="total-order__payment">
  <div class="total-order__col">
    <div class="total-order__text">Итого к оплате:</div>
  </div>
  <div class="total-order__col">
    <div class="total-order__price js-total-order-cost"><span><%= "%.2f" % (@order.discount_total_price_s + delivery_cost.to_f) %></span> сом.</div>
  </div>
</div>
<div class="total-order__button">
  <%= f.submit( payment_method == 'cash' ? "Заказать" : "Перейти к оплате", class: 'total-order__link js-submit-order', data: {disable_with: "Подождите..." }) %>
</div>

app/views/orders/_show.html.slim
.title
  h1 Корзина
.items
  =render @order.order_items
.buy_details
  p.total == "Предварительная сумма: <b>#{total_price @order}</b> *"
  p.delivery_warning == "*Без учета стоимости доставки"

  -if (saving @order).to_i > 0
    p.discount.pink == "Экономия: <strong>#{saving @order }</strong>"
  = link_to "Оформить заказ", edit_order_path(@order)
.close_button &#x2715;

app/views/orders/complete.js.erb
$(".order").remove()
$(".bg").remove()
$("#message").text("Ваш заказ принят! Ждите когда с Вами свяжутся")
$("#message").slideDown()
$(".cart_count").remove();
$("#clear_cart").remove();
$(".currency").append("<%= j render 'orders/order_link' %>")
setTimeout(function(){
    $("#message").slideUp()
  }, 4500);

app/views/orders/edit.html.erb
<div class="order-block">
  <%= form_for @order, html: { id: "user_order_form" } do |form| %>
    <div class="user-order user-order__col-left">
      <div class="user-order__info">
        <div class="user-order__img">
          <%= image_tag('info-ic.svg', alt: "info") %>
        </div>
        <div class="user-order__text">
            <p>Уважаемый покупатель, Вы можете быть уверенны в сохранении конфиденциальности Ваших персональных данных. Вся указанная информация надежно защищена SSL сертификатом. Процесс онлайн оплаты проходит на стороне банка, где гарантирован максимальный уровень защиты данных.</p><br/>
            <p>Для произведения оплаты посредством платежной карты Элкарт Вам необходимо убедиться в том, что у Вас подключена услуга интернет платежей, для этого Вам нужно обратиться в банк, в котором была выпущена платежная карта.</p>
        </div>
      </div>
      <%= render partial: 'orders/order_form', locals: { f: form } %>
    </div>
    <div class="user-order__col-right">
      <div class="total-order">
        <%= render partial: 'orders/order_total', locals: { f: form } %>
      </div>
      <div class="user-order__delivery-warning">
        Стоимость доставки до Вашего адреса следует уточнить у наших менеджеров по следующему номеру телефона: 0555 00 15 39. Оплата за доставку производится наличными при получении заказа.
      </div>
    </div>
  <% end %>
</div>

app/views/orders/edit.js.erb
$('.order').remove()
$("body").append("<div class='order'></div>")
$("#cart").empty().hide();
$(".order").append("<%= j render'orders/form' %>");
$(".bg, .close_button").click(function(){
  $('.bg').remove()
  $('.order').remove()
  $("#cart").hide();
  $("#cart").empty();
});
$(document).keyup(function(e) {

  if (e.keyCode == 27) { 
    $('.bg').remove()
    $('.order').remove()
  }   // esc
});

app/views/orders/empty_cart.js.erb
// $(".cart_count").html('Корзина пуста')
// $('.cart_count').click(function () {return false;});
// $(".currency .clear_cart").remove()
$(".cart_count").remove();
$("#clear_cart").remove();
$(".currency").append("<%= j render 'orders/order_link' %>")
$("#message").text("Все товары удалены из корзины")
$("#message").slideDown()
$("#order_item_quantity").val("1")
setTimeout(function(){
    $("#message").slideUp()
  }, 3500);

app/views/orders/show.js.erb
$("#cart").show()
$("body").append("<div class='bg'></div>")
$("#cart").html("<%= j render('orders/show') %>");
if ($("#cart .items .order_item").length > 2){
  $("#cart .items").css("overflow-y", "scroll")
}
$( "#cart" ).keypress(function() {
  console.log( "Handler for .keypress() called." );
});
$(".bg, .close_button").click(function(){
  $('.bg').remove()
  $("#cart").hide();
  $("#cart").empty();
});
$(document).keyup(function(e) {

  if (e.keyCode == 27) { 
    $('.bg').remove()
    $("#cart").hide();
    $("#cart").empty();
  }   // esc
});