config/routes.rb
# require 'sidekiq/web'
AutoshinaKg::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  # mount Sidekiq::Web => '/sidekiq'
  # authenticate :admin_user do
  #   mount Sidekiq::Web => '/admin/sidekiq'
  # end

  get 'api/products', to: 'api#products'
  get 'api/categories', to: 'api#categories'
  get 'api/categories_fields', to: 'api#categories_fields'
  get 'api/categories_fields_values', to: 'api#categories_fields_values'
  get 'api/products_fields_values', to: 'api#products_fields_values'
  get 'api/parts', to: 'api#parts'
  get 'api/vendors', to: 'api#vendors'


  # get 'products/search', :as => 'search'
  get 'pages/calculator', :as => 'calculator'
  get 'products/fetch_fields', :as => 'fetch_fields'
  get 'products/fetch_field_type', :as => 'fetch_field_type'
  get 'products/conversion_of_currency', :as => 'conversion_of_currency'
  get 'products/update_categories', :as => 'update_categories'
  get 'products/fetch_vendors', :as => 'fetch_vendors'
  get 'products/fetch_product_fields', :as => 'fetch_product_fields'
  get 'products/fetch_fields_sizes', :as => 'fetch_fields_sizes'
  resources :products
  resources :cars
  root 'products#index'
  resources :news_items, path: 'news', only: [:index, :show]
  resources :offer_items, path: 'offers', only: [:index, :show]
  get '/contacts', to: 'pages#contacts'
  get '/about', to: 'pages#about'
  get '/deliver', to: 'pages#deliver'
  get '/rules', to: 'pages#rules'
  get 'vendors/update_vendors', :as => 'update_vendors'
  get 'vendors/select_vendors', :as => 'select_vendors'
  get 'car_models/fetch_models', :as => 'fetch_models'
  get 'categories_fields_values/fetch_categories_fields_values', :as => 'fetch_categories_fields_values'
  get 'categories_fields_values/set_categories_fields_values', :as => 'set_categories_fields_values'
  get 'car_models/fetch_car_models', :as => 'fetch_car_models'
  get 'car_models/fetch_years', :as => 'fetch_years'
  get 'car_models/fetch_modifications', :as => 'fetch_modifications'
  get 'car_models/fetch_sizes', :as => 'fetch_sizes'
  resources :orders, only: [:update, :show, :destroy, :edit]
  resources :order_items, only: [:create, :destroy, :update]
  resources :bookmarks, only: [:update, :show, :destroy]
  resources :bookmark_items, only: [:create, :destroy]
  # resource :order, only: [:update, :show, :destroy] do
  #   resources :order_items, only: [:create, :destroy, :update]
  # end

  get 'payment/cancelled', to: 'payments#cancelled'
  post 'payment/result', to: 'payments#result'
  get 'payment/connection_failed', to: 'payments#connection_failed'

  # get "/system/*path", to: redirect('http://autoshina.kg/system/%{path}.%{format}') if Rails.env.development? && !ENV['ASSETS_HOST']
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  internal_name    :string(255)
#  image            :string(255)
#  video            :string(255)
#  meta_keywords    :string(255)
#  meta_description :text
#  cost             :integer
#  count            :integer
#  vendor_id        :integer
#  category_id      :integer
#  last_edit        :datetime
#  remote_id        :integer
#  part_id          :integer
#  created_at       :datetime
#  updated_at       :datetime
#  featured         :integer          default(0)
#  discount         :integer          default(0)
#

class Product < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  belongs_to :category
  belongs_to :vendor
  belongs_to :part
  has_many :product_fields_values
  accepts_nested_attributes_for :product_fields_values, allow_destroy: true

  validates_presence_of :name, :internal_name, :part_id, :category_id, :vendor_id, :cost, :remote_id, :count
  validates :remote_id, uniqueness: true
  mount_uploader :image, ProductUploader

  paginates_per 24

  # default_scope -> { order("products.updated_at desc") }
  scope :featured, -> { where("featured > 0 and cost >  0").order("featured desc") }
  scope :price_exists, -> { where("products.cost > 0")}
  scope :tires, -> { where("part_id = 1") }
  scope :oils, -> { where("part_id = 2") }
  scope :accumulator, -> { where("part_id = 3") }
  scope :rims, -> { where("part_id = 4") }

  def get_value_by_field field
    self.product_fields_values.joins("LEFT JOIN categories_fields ON categories_fields.id = product_fields_values.categories_field_id").where("categories_fields.field_name = ?", field).first
  end

  def self.search(values=[], vendor="")
    values = (values || []).compact
    conditions = values.map{|val| "lower(product_fields_values.value) IN (" + val.map{|v| "'#{v.mb_chars.downcase.to_s}'" }.join(", ") + ")" }.map{|andc| "(" + andc + ")" }.join(" OR ")
    if values.present? and values.first.size > 0
      Product.joins(:product_fields_values).merge(ProductFieldsValue.where(conditions)).where(vendor).group('products.id').select("products.*").having('COUNT(*) = ?', values.first.size)
    else
      Product.where(vendor)
    end

  end

  def discount_price
    self.cost - ((self.cost/100) * self.discount)
  end

  def currency_price unit
    if unit == "dollar"
      number_to_currency self.conversion_of_currency, format: '%n%u', unit: "$"
    else
      number_to_currency self.cost, format: '%n %u', unit: "сом"
    end
  end

  def conversion_of_currency
    self.cost/SiteSetting.find(1).current_rate
  end

  def currency_and_discount
    c = self.conversion_of_currency.to_f
    c - ((c/100) * self.discount)
  end

  def is_tire?
    self.part_id == 1 ? true : false
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :check_params, only: :fetch_fields
    # before_action :search_values, :vendor, only: :index
    helper_method :sort_column, :sort_direction


  def index
    if params[:model_search]
      @products = Product.where(internal_name: params[:model_search][:size]).price_exists.page(params[:page]).order(sort_column + " " + sort_direction)
    else
      @products = Product.price_exists.search(search_values, query).page(params[:page]).order(sort_column + " " + sort_direction)
    end   

    @featured = Product.featured.where(part_id: 1).limit(25)
  end

  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html do
        @product = Product.find(params[:id])
        @product.increment :featured, 1
        @product.save
      end
      format.js do
        @product = Product.find(params[:id])
      end
    end 
  end

  def fetch_fields
    @fields = Category.find(params[:category_id]).categories_fields.where(show_in_browse: "1") unless params[:category_id].nil?
  end

  def conversion_of_currency
    if cookies[:currency] == "dollar"
      cookies[:currency] = "som"
      redirect_to :back
    else
      cookies[:currency] = "dollar"
      redirect_to :back
    end
  end

  def update_categories
    unless params[:part_id].blank?
      part = Part.find(params[:part_id])
      @categories = part.categories.map{|a| [a.name, a.id]}.unshift ["Выберите категорию", ""]
    else
      @categories = [["",""]]
    end
  end

  def fetch_vendors
    unless params[:category_id].blank?
      category = Category.find(params[:category_id])
      @vendors = category.vendors.map{|a| [a.name, a.id]}.unshift ["Выберите производителя", ""]
    else
      @vendors = [["",""]]
    end
  end

  def fetch_product_fields
    # binding.pry
    sleep 0.2
    category = Category.find(params[:category_id])
    @categories_fields = category.categories_fields.map{|a| [a.field_name, a.id]}
  end

  def fetch_field_type
    field = CategoriesField.find params[:category_field_id]
    if field.type_field == "html_text_area"
      render json: {}, status: 200
    else
      render json: {}, status: 504
    end
  end

  private
    def check_params
      unless params[:category_id].present?
        render nothing: true
        return false 
      end
    end



    def search_values
      season_vars = Array.new
      # binding.pry
      if params[:search_size]
        search_size = Array.new
        params[:search_size].each do |key, value|
          search_size.push value if value.present? and key =~ /^field_[0-9]/
          # values.push key.split("field_").last if value.present? and key =~ /^field_[a-я]/
        end
      end
      if params[:search_season]
        search_season = params[:search_season].keys
      end
      if search_season.present? and search_size.present?
        return season_vars = search_season.map{|s| [s] + search_size }
      end
      if search_season.nil?
        return season_vars << search_size
      elsif search_size.nil?
        return season_vars << search_season
      elsif search_season and search_size.empty?
        return season_vars = search_season.map{|s| [s]}
      end
    end

    def query
      query = String.new
      if params[:search_type]
        query = "#{"part_id = #{params[:search_type][:part_id]}"}" if params[:search_type][:part_id].present?
        query = "#{"category_id = #{params[:search_type][:category_id]}"}" if params[:search_type][:category_id].present?
        query = "#{"vendor_id = #{params[:search_type][:vendor_id]}"}" if params[:search_type][:vendor_id].present?
      end
      query
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/products_helper.rb
module ProductsHelper

  def currency_checked product
    if cookies[:currency] == "dollar"
      product.currency_price("dollar")
    else
      product.currency_price("som")
    end
  end

  def discount product
    if cookies[:currency] == "dollar"
      p = product.conversion_of_currency.to_f
      dst = p - ((p/100) * product.discount)
      number_to_currency dst, format: '%n%u', unit: "$"
    else
      number_to_currency product.discount_price, format: '%n %u', unit: "сом"
    end
  end

  def price_difference product
    if cookies[:currency] == "dollar"
      p = product.conversion_of_currency.to_f
      dst = p - ((p/100) * product.discount)
      number_to_currency (p-dst), format: '%n%u', unit: "$"
    else
      number_to_currency (product.cost - product.discount_price), format: '%n %u', unit: "сом"
    end
  end

  def order_price_difference order
    if cookies[:currency] == "dollar"
      p = order.currency_total_price
      dst = p - ((p/100) * product.discount)
      number_to_currency (p-dst), format: '%n%u', unit: "$"
    else
      number_to_currency (order.total_price - order.discount_total_price_s), format: '%n %u', unit: "сом"
    end
  end

  def total_price order
    if cookies[:currency] == "dollar"
     number_to_currency order.discount_total_price_d, format: '%n%u', unit: "$"
    else
     number_to_currency order.discount_total_price_s, format: '%n %u', unit: "сом"
    end
  end

  def saving order
    if cookies[:currency] == "dollar"
      number_to_currency order.currency_total_price - order.discount_total_price_d, format: '%n%u', unit: "$"
    else
      number_to_currency (order.total_price - order.discount_total_price_s), format: '%n %u', unit: "сом"
    end
  end

  def type_helper part
    case part.name
    when "Шины"
      "шины"
    when "Автомасла"
      "масла"
    when "Аккумуляторы"
      "аккумулятора"
    when "Диски"
      "диска"
    else
      ""
    end
  end

end

app/views/products/_product.html.slim
.product
  .p_icons
    - if product.featured > 50
      .pop
    - if product.discount > 0
      .dis
    - if @bookmark.products.include? product
      .bmarks
  .image
    = link_to (image_tag product.image.thumb.url), product 
    = link_to "Просмотр", product, class: "show" ,remote: true
  .short_description
    h2 = link_to product.vendor.name, product
    h2 
      = link_to product.name, product, title: "#{product.name}", class: "hover"
      span.grad
      / .show_title
      /   div = product.name
    .param

      -if product.part.id == 1
        p = link_to "Размер: #{product.internal_name}", product
        p = link_to "Наличие: #{ (product.count > 3) ? 'На складе' : product.count}", product
        -if product.get_value_by_field 'Сезонность'
          p = link_to "Сезонность: #{product.get_value_by_field('Сезонность').value}", product
      -elsif product.part.id == 2
        -if product.get_value_by_field('Объем(л.)').present?
          p = link_to "Объем(л.): #{product.get_value_by_field('Объем(л.)').value}", product
        -elsif product.get_value_by_field('Объем(кг.)').present?
          p = link_to "Объем(кг.): #{product.get_value_by_field('Объем(кг.)').value}", product
        -if product.get_value_by_field 'Сезонность'
          p = link_to "Сезонность: #{product.get_value_by_field('Сезонность').value}", product
        p = link_to "Наличие: #{ (product.count > 1) ? 'На складе' : product.count}", product
      -elsif product.part.id == 3
        -if product.get_value_by_field('Полярность').present?
          p = link_to "Полярность: #{product.get_value_by_field('Полярность').value}", product
        -if product.get_value_by_field('Емкость').present?
          p = link_to "Емкость: #{product.get_value_by_field('Емкость').value}", product
        -if product.get_value_by_field('Ток').present?
          p = link_to "Ток: #{product.get_value_by_field('Ток').value}", product
        -if product.get_value_by_field('Клеммы').present?
          p = link_to "Клеммы: #{product.get_value_by_field('Клеммы').value}", product
        p = link_to "Наличие: #{ (product.count > 1) ? 'На складе' : product.count}", product
      -elsif product.part.id == 4
        -if product.get_value_by_field('Ширина').present?
          p = link_to "Ширина: #{product.get_value_by_field('Ширина').value}", product
        -if product.get_value_by_field('Емкость').present?
          p = link_to "Диаметр: #{product.get_value_by_field('Емкость').value}", product
        -if product.get_value_by_field('Диаметр').present?
          p = link_to "Крепеж: #{product.get_value_by_field('Диаметр').value}", product
        -if product.get_value_by_field('Вылет').present?
          p = link_to "Вылет: #{product.get_value_by_field('Вылет').value}", product
        -if product.get_value_by_field('Вылет(ET)').present?
          p = link_to "Вылет(ET): #{product.get_value_by_field('Вылет(ET)').value}", product
        -if product.get_value_by_field('ЦО(Dia)').present?
          p = link_to "ЦО(Dia): #{product.get_value_by_field('ЦО(Dia)').value}", product
        p = link_to "Наличие: #{ (product.count > 1) ? 'На складе' : product.count}", product
    - if product.discount > 0
      p.gray_price = link_to "Цена: <strong class='curr'>#{currency_checked product}</strong>".html_safe
      / -binding.pry
      p.pink = link_to "Акция: <strong class='curr'>#{discount product}</strong>".html_safe, product
    -else
      p = link_to "Цена: <strong class='curr'>#{currency_checked product}</strong>".html_safe, product

app/views/products/_products_empty.html.slim
p НИЧЕГО НЕ НАЙДЕНО

app/views/products/conversion_of_currency.js.erb
$(".currency ul").empty()
$(".currency ul").html("<%= j render 'shared/currency' %>")
<% if cookies[:currency] == "dollar" %>
  $(".curr").each(function( index ) {
    price = $( this ).text();
    $( this ).text((price/54).toFixed(0))
  });
<% elsif cookies[:currency] == "som" %>
  $(".curr").each(function( index ) {
    price = $( this ).text();
    $( this ).text((price*54).toFixed(0))
  });
<% end %>

app/views/products/fetch_fields.js.erb
<%- if params[:type] == "1" %>

  $(".tire_fields").empty();
  $(".tire_fields").append(
    '<%= j (select_tag "search_type[vendor_id]", options_for_select((Category.find(params[:category_id]).vendors.map { |v| [v.name, v.id] }).insert(0, ["Производитель", ""]), vendor_checked), {id: "tire_vendor"}) %>'
    );
  <%- @fields.where(search_type: "select").each do |field| %>
      <%- values = field.categories_fields_values %>
      $(".tire_fields").append(
        '<%= j (select_tag "search_size[field_#{field.id}]", options_for_select((values.order("value asc").map { |c| [c.value, c.value] }).insert(0, ["#{field.field_name}", ""])), {id: "field_#{field.id}"}) %>'
        );
  <% end %>
  $(".tire_checkbox").empty();
  <%- @fields.where(search_type: "checkbox").each do |field| %>
      <%- values = field.categories_fields_values %>
      <% values.each do |v| %>
        $(".tire_checkbox").append("<div class='checkbox_field'></div>");
        $(".checkbox_field:last").append('<%= check_box_tag "search_season[#{v.value}]", nil,false,id: "checkbox_#{v.id}" %>'); 
        $(".checkbox_field:last").append('<%= label_tag("checkbox_#{v.id}", "#{v.value}") %>');
      <% end %>
  <% end %>
  
<%- elsif params[:type] == "2" %>
  $(".oil_fields").empty();
  $(".oil_fields").append(
    '<%= j (select_tag "search_type[vendor_id]", options_for_select((Category.find(params[:category_id]).vendors.map { |v| [v.name, v.id] }).insert(0, ["Производитель", ""])), {id: "oil_vendor"}) %>'
    );
  <%- @fields.where(search_type: "select").each do |field| %>
      <%- values = field.categories_fields_values %>

      $(".oil_fields").append(
        '<%= j (select_tag "search_size[field_#{field.id}]", options_for_select((values.order("value asc").map { |c| ["#{field.field_name}: #{c.value}", c.value] }).insert(0, ["#{field.field_name}", ""])), {id: "field_#{field.id}"}) %>'
        );
  <% end %>
  $(".tire_checkbox, .oil_checkbox").empty();
  <%- @fields.where(search_type: "checkbox").each do |field| %>
      <%- values = field.categories_fields_values %>
      <% values.each do |v| %>
        $(".oil_checkbox").append('<%= label_tag("checkbox_#{v.id}", "#{v.value}") %>');
        $(".oil_checkbox").append('<%= check_box_tag "search_season[check_#{v.value}]", nil,false, id: "checkbox_#{v.id}" %>'); 
      <% end %>
  <% end %>
<%- end %>

app/views/products/fetch_product_fields.js.erb
$('.has_many_container select').last().html("<%= escape_javascript(options_for_select(@categories_fields)) %>");

app/views/products/fetch_vendors.js.erb
if ($('#product_vendor_id').length != 0){
  $('#product_vendor_id').html("<%= escape_javascript(options_for_select(@vendors)) %>");
}

app/views/products/index.html.slim
= render "shared/featured_products"
.products
  .title
    h1 Каталог
  -if @products.any?
    .sort
      ul
        p Сортировка
        li = sortable "name", "По названию"
        li = sortable "cost", "По цене"
    = render @products
  -else
    =render "products/products_empty" 
#next_page
  = paginate @products
#more
  p Еще

app/views/products/index.js.erb
$(".products").append("<%= escape_javascript(render(@products)) %>")
<% if @products.next_page %>
  $('.pagination').replaceWith('<%= j paginate(@products) %>');
  // $('.filter').removeClass('filter-absolute');
  // $('.filter').addClass('filter-fixed');
  n = $(".nav-box").offset().top - $('.filter').offset().top
  // f = $('.filter').offset().top
  $('.filter-absolute').animate({top: $(".nav-box").offset().top + n}, 200, function(){
    $('.filter').removeClass('filter-absolute');
    $('.filter').addClass('filter-fixed');
    $('.filter-fixed').css('top', 83);
  });

<% else %>
  $('.pagination').remove();
  $('#more').remove();
<% end %>

app/views/products/show.html.slim
-provide(:title, "#{@product.name} - #{@product.vendor.name} -")
-provide(:description, "#{@product.meta_description}")
-provide(:keywords, "#{@product.meta_keywords}")
.product_show
  .product_info
    .product_block
      .p_icons
        - if @product.featured > 50
          .pop
        - if @product.discount > 0
          .dis
        - if @bookmark.products.include? @product
          .bmarks
      = image_tag @product.image.url :show
      = link_to "Просмотр", @product, class: "show" ,remote: true
    .product_block
      .block_info
        h2 = @product.vendor.name
        h2 = @product.name
        .param
          - @product.product_fields_values.each do |field|
            p = "#{field.categories_field.field_name}: #{field.value}" if field.categories_field.field_name != "Описание"
          - if @product.discount > 0
            p.gray_price = "Цена: <strong class='curr'>#{currency_checked @product}</strong>".html_safe 
          -else
            p = "Цена: <strong class='curr'>#{currency_checked @product}</strong>".html_safe 
      .product_buy
        = button_to "Добавить в закладки", bookmark_items_path(bookmark_item: {product_id: @product.id}), class: "bookmarks",remote: true
        / == link_to "Добавить в закладки", bookmark_items_path
        / =binding.pry
        - if @product.cost > 0
          =form_tag order_items_path, class: "add_pr" ,remote: true do
            = text_field_tag "order_item[quantity]", "1"
            span шт.
            = hidden_field_tag "order_item[product_id]", @product.id
            = submit_tag "Купить"
            / = button_tag "Button Text", :class => "btn", :type => "submit"
    .product_block
      - if @product.discount > 0
        .discount_block
          p  На данный товар действует специальная скидка!
          p == "Цена: <strong>#{discount @product}</strong>"
  - unless @product.get_value_by_field('Описание').nil?
    .product_description
      .product_block
        h3 ="Основные особенности #{type_helper @product.part}"
      .description
        = @product.get_value_by_field('Описание').value.html_safe
  - unless @product.video.blank?
    .product_video
      .product_block
        h3 Видео
      .video
        = @product.video.html_safe

app/views/products/show.js.erb
$('body').append("<div class='bg' id='bg'></div>");
$('body').append("<div class='modal' id='modal' ></div>");
$('.modal').addClass( "image_show" );
$('.image_show').append("<%= j image_tag @product.image.url(:show) %>");
$('.image_show').append("<div class='close_button'>&#10005;</div>");
$(".close_button, .bg").click(function(){
  $('.modal').remove();
  $('.bg').remove();
})
$(document).keyup(function(e) {

  if (e.keyCode == 27) { 
    $('.bg').remove()
    $("#modal").remove()
  }   // esc
});

app/views/products/update_categories.js.erb
if ($('#product_category_id').length != 0){
  $('#product_category_id').html("<%= escape_javascript(options_for_select(@categories)) %>");
}